"""add search_slots table

Revision ID: 71293ea010aa
Revises: 21d81cdb89a5
Create Date: 2026-06-17 23:07:15.355674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71293ea010aa'
down_revision: Union[str, Sequence[str], None] = '21d81cdb89a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=False),
    sa.Column('search_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'county', 'industry', 'search_term', name='search_slots_unique')
    )
    # Guard against partial previous runs that may have already applied this constraint
    conn = op.get_bind()
    exists = conn.execute(sa.text(
        "SELECT 1 FROM pg_constraint WHERE conname = 'leads_run_external_unique'"
    )).fetchone()
    if not exists:
        with op.batch_alter_table('leads', schema=None) as batch_op:
            batch_op.create_unique_constraint('leads_run_external_unique', ['run_id', 'external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('leads_run_external_unique', type_='unique')

    op.drop_table('search_slots')
    # ### end Alembic commands ###
